onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /idtoexreg/operation
add wave -noupdate /idtoexreg/upperImmVal
add wave -noupdate /idtoexreg/s_TypeSel
add wave -noupdate /idtoexreg/s_FlushOrReset
add wave -noupdate /idtoexreg/reg_w_enANDAlu_write
add wave -noupdate /idtoexreg/operation
add wave -noupdate /idtoexreg/o_upperImmVal
add wave -noupdate /idtoexreg/o_reg_w_enANDAlu_write
add wave -noupdate /idtoexreg/o_operation
add wave -noupdate /idtoexreg/o_issv
add wave -noupdate /idtoexreg/o_isUnsignedALU
add wave -noupdate /idtoexreg/o_isLoadU
add wave -noupdate /idtoexreg/o_isLoad
add wave -noupdate /idtoexreg/o_isLinkALU
add wave -noupdate /idtoexreg/o_isLink
add wave -noupdate /idtoexreg/o_isJumpReg
add wave -noupdate /idtoexreg/o_instMem
add wave -noupdate /idtoexreg/o_dmem_w_en
add wave -noupdate /idtoexreg/o_branchAnd
add wave -noupdate /idtoexreg/o_branchALU
add wave -noupdate /idtoexreg/o_UpperImm
add wave -noupdate /idtoexreg/o_TypeSel
add wave -noupdate /idtoexreg/o_Reg_w_en
add wave -noupdate /idtoexreg/o_RegDst
add wave -noupdate /idtoexreg/o_RegData2
add wave -noupdate /idtoexreg/o_RegData1
add wave -noupdate /idtoexreg/o_PCplus4
add wave -noupdate /idtoexreg/o_IsImmALU
add wave -noupdate /idtoexreg/o_ImmSignExt
add wave -noupdate /idtoexreg/o_ALUsel
add wave -noupdate /idtoexreg/o_ALU_write
add wave -noupdate /idtoexreg/o_ALU_OP
add wave -noupdate /idtoexreg/issv
add wave -noupdate /idtoexreg/isUnsignedALU
add wave -noupdate /idtoexreg/isLinkALU
add wave -noupdate /idtoexreg/isJumpReg
add wave -noupdate /idtoexreg/instMem
add wave -noupdate /idtoexreg/dmem_w_en
add wave -noupdate /idtoexreg/branchAnd
add wave -noupdate /idtoexreg/branchALU
add wave -noupdate /idtoexreg/WE
add wave -noupdate /idtoexreg/UpperImm
add wave -noupdate /idtoexreg/TypeSel
add wave -noupdate /idtoexreg/Reset
add wave -noupdate /idtoexreg/Reg_w_en
add wave -noupdate /idtoexreg/RegDst
add wave -noupdate /idtoexreg/RegData2
add wave -noupdate /idtoexreg/RegData1
add wave -noupdate /idtoexreg/PCplus4
add wave -noupdate /idtoexreg/IsLoadU
add wave -noupdate /idtoexreg/IsLoad
add wave -noupdate /idtoexreg/IsLink
add wave -noupdate /idtoexreg/IsImmALU
add wave -noupdate /idtoexreg/ImmSignExt
add wave -noupdate /idtoexreg/Flush
add wave -noupdate /idtoexreg/Clk
add wave -noupdate /idtoexreg/ALUsel
add wave -noupdate /idtoexreg/ALU_write
add wave -noupdate /idtoexreg/ALU_OP
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1001 ns}
