vsim -novopt work.mips_pipelined_processor
# vsim -novopt work.mips_pipelined_processor 

add wave -position end  sim:/mips_pipelined_processor/CLK
add wave -position end  sim:/mips_pipelined_processor/regfile_reset
add wave -position end  sim:/mips_pipelined_processor/PC_reset
add wave -position end  sim:/mips_pipelined_processor/IFID_reset
add wave -position end  sim:/mips_pipelined_processor/IFID_flush
add wave -position end  sim:/mips_pipelined_processor/IFID_w_en
add wave -position end  sim:/mips_pipelined_processor/IDEX_reset
add wave -position end  sim:/mips_pipelined_processor/IDEX_flush
add wave -position end  sim:/mips_pipelined_processor/IDEX_WE
add wave -position end  sim:/mips_pipelined_processor/EXMEM_reset
add wave -position end  sim:/mips_pipelined_processor/EXMEM_flush
add wave -position end  sim:/mips_pipelined_processor/EXMEM_WE
add wave -position end  sim:/mips_pipelined_processor/MEMWB_reset
add wave -position end  sim:/mips_pipelined_processor/MEMWB_flush
add wave -position end  sim:/mips_pipelined_processor/MEMWB_WE
add wave -position end  sim:/mips_pipelined_processor/forwardA_branch
add wave -position end  sim:/mips_pipelined_processor/forwardB_branch
add wave -position end  sim:/mips_pipelined_processor/forwardA_ALU
add wave -position end  sim:/mips_pipelined_processor/forwardB_ALU
force -freeze sim:/mips_pipelined_processor/CLK 1 0, 0 {50 ns} -r 100
force -freeze sim:/mips_pipelined_processor/regfile_reset 1 0
noforce sim:/mips_pipelined_processor/PC_reset
force -freeze sim:/mips_pipelined_processor/PC_reset 1 0
force -freeze sim:/mips_pipelined_processor/IFID_reset 1 0
force -freeze sim:/mips_pipelined_processor/IFID_flush 0 0
force -freeze sim:/mips_pipelined_processor/IFID_w_en 1 0
force -freeze sim:/mips_pipelined_processor/IDEX_reset 1 0
force -freeze sim:/mips_pipelined_processor/IDEX_flush 0 0
force -freeze sim:/mips_pipelined_processor/IDEX_WE 1 0
force -freeze sim:/mips_pipelined_processor/EXMEM_reset 1 0
force -freeze sim:/mips_pipelined_processor/EXMEM_flush 0 0
force -freeze sim:/mips_pipelined_processor/EXMEM_WE 1 0
force -freeze sim:/mips_pipelined_processor/MEMWB_reset 1 0
force -freeze sim:/mips_pipelined_processor/MEMWB_flush 0 0
force -freeze sim:/mips_pipelined_processor/MEMWB_WE 1 0
force -freeze sim:/mips_pipelined_processor/forwardA_branch 000 0
force -freeze sim:/mips_pipelined_processor/forwardB_branch 000 0
force -freeze sim:/mips_pipelined_processor/forwardA_ALU 000 0
force -freeze sim:/mips_pipelined_processor/forwardB_ALU 000 0

run

force -freeze sim:/mips_pipelined_processor/regfile_reset 0 0
force -freeze sim:/mips_pipelined_processor/PC_reset 0 0
force -freeze sim:/mips_pipelined_processor/IFID_reset 0 0
force -freeze sim:/mips_pipelined_processor/IDEX_reset 0 0
force -freeze sim:/mips_pipelined_processor/EXMEM_reset 0 0
force -freeze sim:/mips_pipelined_processor/MEMWB_reset 0 0

run
run

add wave -position end  sim:/mips_pipelined_processor/IF_stage1/CLK
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/PC_reset
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/IFID_reset
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/MEMWB_isJumpReg
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/mux_ORval
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/reg_WE
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/IDEX_branchJump
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/IDEX_rs
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/o_instMem
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/o_PCplus4
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_IF_IMEM
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_PCp4
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_PC_val
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_mux1_out
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_mux2_out
add wave -position end  sim:/mips_pipelined_processor/IF_stage1/s_reg_WE

add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/CLK
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IDEX_reset
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/Regfile_reset
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IDEX_WE
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IDEX_Flush
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IFID_AdderVal
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IFID_instMem
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_instMem
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_upperImmVal
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/ValtoReg_File
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MemWB_PCPlus4
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_ALUWrite
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_isLinkALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_RegDest
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MEMWB_IsLink
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MemWB_upperImm
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/MemWB_RegW_en
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/forwardA_Branch
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/forwardB_Branch
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/ExMem_ALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IDEX_ALUval
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/EXMEM_PCplus4
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/EXMEM_UpperImm
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/IDEX_UpperImm
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_IFID_instMem
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_branchAnd
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_operation
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_ALUsel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_issv
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isJumpReg
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isLinkALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_ALU_write
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isUnsignedALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_IsImmALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_reg_w_enANDAlu_write
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_RegDst
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isLoadU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_Reg_w_en
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_UpperImm
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isLink
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_dmem_w_en
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_isLoad
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_branch_jump_mux
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_muxORval
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_TypeSel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_ALU_OP
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_RegData1
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_RegData2
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_ImmSignExt
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_PCplus4
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_upperImmVal
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/o_branchALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux7
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux8
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux20_Out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux9_Out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/ALU_out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_muxX_Out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux12_Out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux4
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux5
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux6
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux15
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux8_select
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux20sel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_BranchOut
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_zero
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_mux_ORVAlue
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isRtype
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_isJumpReg
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_isLinkALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_ALU_write
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_isUnsignedALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_issv
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_o_reg_w_enANDAlu_write
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_branch_Sel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_operation
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/ALUOp
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/lstypesel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_ALUsel
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_ImmSignExt
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/branch_shifter_out
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_NbitAdder
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_jump_addr
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/fwd_out_1
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/fwd_out_2
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_o_RegData1
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_o_RegData2
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_UpperImmVal
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/link
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/bgtz_blez
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isLink
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_BranchControl
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_Jump
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isJumpReg
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_isBranchLink
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/s_Reg_wen
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/dmem_w_en
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isLoadU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isLoad
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/RegDst
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/UpperImm
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isImmALU
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/CompareZero
add wave -position end  sim:/mips_pipelined_processor/ID_stage_1/isBranch

add wave -position 142  sim:/mips_pipelined_processor/ID_stage_1/Register_file/CLK
add wave -position 143  sim:/mips_pipelined_processor/ID_stage_1/Register_file/rs_sel
add wave -position 144  sim:/mips_pipelined_processor/ID_stage_1/Register_file/rt_sel
add wave -position 145  sim:/mips_pipelined_processor/ID_stage_1/Register_file/w_data
add wave -position 146  sim:/mips_pipelined_processor/ID_stage_1/Register_file/w_sel
add wave -position 147  sim:/mips_pipelined_processor/ID_stage_1/Register_file/w_en
add wave -position 148  sim:/mips_pipelined_processor/ID_stage_1/Register_file/reset
add wave -position 149  sim:/mips_pipelined_processor/ID_stage_1/Register_file/rs_data
add wave -position 150  sim:/mips_pipelined_processor/ID_stage_1/Register_file/rt_data
add wave -position 151  sim:/mips_pipelined_processor/ID_stage_1/Register_file/decoder_out
add wave -position 152  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_A
add wave -position 153  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_B
add wave -position 154  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_C
add wave -position 155  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_D
add wave -position 156  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_E
add wave -position 157  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_F
add wave -position 158  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_G
add wave -position 159  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_H
add wave -position 160  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_I
add wave -position 161  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_J
add wave -position 162  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_K
add wave -position 163  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_L
add wave -position 164  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_M
add wave -position 165  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_N
add wave -position 166  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_O
add wave -position 167  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_P
add wave -position 168  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_Q
add wave -position 169  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_R
add wave -position 170  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_S
add wave -position 171  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_T
add wave -position 172  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_U
add wave -position 173  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_V
add wave -position 174  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_W
add wave -position 175  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_X
add wave -position 176  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_Y
add wave -position 177  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_Z
add wave -position 178  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AA
add wave -position 179  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AB
add wave -position 180  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AC
add wave -position 181  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AD
add wave -position 182  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AE
add wave -position 183  sim:/mips_pipelined_processor/ID_stage_1/Register_file/i_AF
add wave -position 184  sim:/mips_pipelined_processor/ID_stage_1/Register_file/a_out



